version: '3'
services:
  web:
    build: .
    container_name: web
    ports:
      - ${WEB_PORT}
    restart: always

  database:
    container_name: database
    image: 'postgres:latest'
    ports:
      - ${POSTGRES_PORT}
    env_file: .env
